import type {
  DataSource,
  IngestionRun,
  SchemaMapping,
  SourceCategory,
  SourceKind,
} from '@/types/sources';

const now = () => new Date().toISOString();
const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const hoursAgo = (h: number) => minutesAgo(h * 60);

export const CATEGORY_LABEL: Record<SourceCategory, string> = {
  database: 'Databases',
  file: 'Files',
  streaming: 'Streaming',
  cloud_storage: 'Cloud storage',
  api: 'APIs',
};

export const KIND_LABEL: Record<SourceKind, string> = {
  postgres: 'PostgreSQL',
  mysql: 'MySQL',
  mongodb: 'MongoDB',
  neo4j: 'Neo4j',
  tigergraph: 'TigerGraph',
  snowflake: 'Snowflake',
  bigquery: 'BigQuery',
  csv: 'CSV',
  json: 'JSON',
  excel: 'Excel',
  parquet: 'Parquet',
  kafka: 'Kafka',
  webhook: 'Webhooks',
  event_stream: 'Event stream',
  sse: 'SSE',
  s3: 'AWS S3',
  gcs: 'Google Cloud Storage',
  azure_blob: 'Azure Blob',
  rest_api: 'REST API',
  graphql: 'GraphQL',
  blockchain: 'Blockchain feed',
  financial_feed: 'Financial feed',
  sanctions_feed: 'Sanctions feed',
};

export const KIND_TO_CATEGORY: Record<SourceKind, SourceCategory> = {
  postgres: 'database',
  mysql: 'database',
  mongodb: 'database',
  neo4j: 'database',
  tigergraph: 'database',
  snowflake: 'database',
  bigquery: 'database',
  csv: 'file',
  json: 'file',
  excel: 'file',
  parquet: 'file',
  kafka: 'streaming',
  webhook: 'streaming',
  event_stream: 'streaming',
  sse: 'streaming',
  s3: 'cloud_storage',
  gcs: 'cloud_storage',
  azure_blob: 'cloud_storage',
  rest_api: 'api',
  graphql: 'api',
  blockchain: 'api',
  financial_feed: 'api',
  sanctions_feed: 'api',
};

/** Catalog of available source kinds the user can connect (the "add source" menu). */
export const AVAILABLE_KINDS: SourceKind[] = [
  'postgres',
  'mysql',
  'mongodb',
  'neo4j',
  'tigergraph',
  'snowflake',
  'bigquery',
  'csv',
  'json',
  'excel',
  'parquet',
  'kafka',
  'webhook',
  'event_stream',
  'sse',
  's3',
  'gcs',
  'azure_blob',
  'rest_api',
  'graphql',
  'blockchain',
  'financial_feed',
  'sanctions_feed',
];

/** Initial connected sources — believable, enterprise-shaped names. */
export const INITIAL_SOURCES: DataSource[] = [
  {
    id: 'src_kyc_pg',
    name: 'KYC core · PostgreSQL',
    kind: 'postgres',
    category: 'database',
    status: 'connected',
    health: 'healthy',
    cadence: 'every_15m',
    uri: 'postgres://kyc-core.prod.internal:5432/kyc',
    region: 'us-east-1',
    connectedAt: hoursAgo(720),
    lastSyncAt: minutesAgo(4),
    rowsIngested: 18_421_092,
    entitiesProduced: 2_641_204,
    edgesProduced: 5_817_321,
    owner: 'Compliance · KYC',
    description: '17M customer records — PII vaulted, only IDs/relationships extracted',
    errorCount: 0,
    credentialRef: 'vault:kyc-rw-2024-06',
  },
  {
    id: 'src_payments_kafka',
    name: 'Payments event stream · Kafka',
    kind: 'kafka',
    category: 'streaming',
    status: 'syncing',
    health: 'healthy',
    cadence: 'realtime',
    uri: 'kafka://broker.payments.internal:9092/txn.events.v3',
    region: 'eu-west-1',
    connectedAt: hoursAgo(2160),
    lastSyncAt: minutesAgo(0),
    rowsIngested: 942_188_402,
    entitiesProduced: 18_244_022,
    edgesProduced: 124_811_404,
    owner: 'Payments · Fraud Ops',
    description: 'Live transaction events · ~14k/s peak',
    errorCount: 2,
    credentialRef: 'vault:kafka-sasl-2024-03',
  },
  {
    id: 'src_wires_snow',
    name: 'Wire transfers · Snowflake',
    kind: 'snowflake',
    category: 'database',
    status: 'connected',
    health: 'healthy',
    cadence: 'hourly',
    uri: 'snowflake://acct.eu-central-1/FRAUD_WH/PUBLIC.WIRES',
    region: 'eu-central-1',
    connectedAt: hoursAgo(1440),
    lastSyncAt: minutesAgo(38),
    rowsIngested: 412_882_004,
    entitiesProduced: 9_122_004,
    edgesProduced: 28_412_887,
    owner: 'AML · Cross-border',
    description: 'SWIFT / SEPA wire reference data, normalized',
    errorCount: 0,
    credentialRef: 'vault:snow-fr-rw',
  },
  {
    id: 'src_ofac',
    name: 'OFAC sanctions feed',
    kind: 'sanctions_feed',
    category: 'api',
    status: 'connected',
    health: 'healthy',
    cadence: 'daily',
    uri: 'https://api.treasury.gov/ofac/sdn/v2',
    connectedAt: hoursAgo(720),
    lastSyncAt: hoursAgo(6),
    rowsIngested: 18_402,
    entitiesProduced: 18_402,
    edgesProduced: 41_811,
    owner: 'Compliance · Sanctions',
    description: 'Specially Designated Nationals + EU + UN consolidated lists',
    errorCount: 0,
    credentialRef: 'vault:treasury-2024',
  },
  {
    id: 'src_card_csv',
    name: 'Card declines · CSV drop',
    kind: 'csv',
    category: 'file',
    status: 'connected',
    health: 'degraded',
    cadence: 'daily',
    uri: 's3://shadow-intel/inbox/card-declines/*.csv',
    connectedAt: hoursAgo(168),
    lastSyncAt: hoursAgo(11),
    rowsIngested: 4_822_011,
    entitiesProduced: 612_341,
    edgesProduced: 1_488_902,
    owner: 'Card Fraud Ops',
    description: 'Daily card-decline export from acquirer · UTF-8 CSV',
    errorCount: 14,
    credentialRef: 'iam:role/csv-drop-reader',
  },
  {
    id: 'src_chain_eth',
    name: 'Ethereum chain feed',
    kind: 'blockchain',
    category: 'api',
    status: 'connected',
    health: 'healthy',
    cadence: 'realtime',
    uri: 'wss://mainnet.infura.io/ws/v3/****',
    region: 'global',
    connectedAt: hoursAgo(2880),
    lastSyncAt: minutesAgo(1),
    rowsIngested: 11_204_902_882,
    entitiesProduced: 22_811_402,
    edgesProduced: 188_402_104,
    owner: 'Crypto Fraud',
    description: 'Mainnet block + transaction stream, wallets clustered',
    errorCount: 0,
    credentialRef: 'vault:infura-eth-2024',
  },
  {
    id: 'src_devices_mongo',
    name: 'Device fingerprints · MongoDB',
    kind: 'mongodb',
    category: 'database',
    status: 'connected',
    health: 'healthy',
    cadence: 'every_15m',
    uri: 'mongodb+srv://fingerprint-prod.shadow.internal/devices',
    region: 'us-east-1',
    connectedAt: hoursAgo(960),
    lastSyncAt: minutesAgo(9),
    rowsIngested: 102_499_021,
    entitiesProduced: 22_104_402,
    edgesProduced: 88_244_011,
    owner: 'Risk Engineering',
    description: 'Browser + mobile fingerprint corpus with rotation history',
    errorCount: 0,
    credentialRef: 'vault:mongo-fp-ro',
  },
  {
    id: 'src_s3_warehouse',
    name: 'Procurement archive · S3',
    kind: 's3',
    category: 'cloud_storage',
    status: 'paused',
    health: 'idle',
    cadence: 'manual',
    uri: 's3://shadow-intel-archive/procurement/*.parquet',
    region: 'us-east-1',
    connectedAt: hoursAgo(1440),
    lastSyncAt: hoursAgo(168),
    rowsIngested: 88_402_104,
    entitiesProduced: 1_812_402,
    edgesProduced: 5_888_402,
    owner: 'Procurement Audit',
    description: 'Vendor PO + payment ledger archive (Parquet, partitioned by year)',
    errorCount: 0,
    credentialRef: 'iam:role/archive-reader',
  },
  {
    id: 'src_graphql_addr',
    name: 'Address registry · GraphQL',
    kind: 'graphql',
    category: 'api',
    status: 'configured',
    health: 'idle',
    cadence: 'hourly',
    uri: 'https://reg.addresses.gov/graphql',
    connectedAt: hoursAgo(48),
    rowsIngested: 0,
    entitiesProduced: 0,
    edgesProduced: 0,
    owner: 'Compliance · Verification',
    description: 'Government-registered address registry · awaiting schema mapping',
    errorCount: 0,
    credentialRef: 'vault:reg-addresses-2024',
  },
  {
    id: 'src_warehouse_bq',
    name: 'Account ledger · BigQuery',
    kind: 'bigquery',
    category: 'database',
    status: 'connected',
    health: 'healthy',
    cadence: 'hourly',
    uri: 'bigquery://prod-eu/ledger.account_movements_v2',
    region: 'eu-west-1',
    connectedAt: hoursAgo(2160),
    lastSyncAt: minutesAgo(28),
    rowsIngested: 2_488_402_104,
    entitiesProduced: 14_402_104,
    edgesProduced: 64_802_104,
    owner: 'Finance · Ledger',
    description: 'Account movements with hashed identifiers',
    errorCount: 0,
    credentialRef: 'vault:bq-prod-eu',
  },
  {
    id: 'src_webhook_signals',
    name: 'Vendor risk signals · Webhook',
    kind: 'webhook',
    category: 'streaming',
    status: 'error',
    health: 'failing',
    cadence: 'realtime',
    uri: 'https://intel.shadow.internal/in/risk-signals',
    connectedAt: hoursAgo(72),
    lastSyncAt: hoursAgo(2),
    rowsIngested: 88_402,
    entitiesProduced: 14_402,
    edgesProduced: 41_802,
    owner: 'Vendor Risk',
    description: 'Third-party risk signal push · auth failing (HTTP 401)',
    errorCount: 41,
    credentialRef: 'vault:vendor-risk-2024',
  },
  {
    id: 'src_sft_excel',
    name: 'STR filings · Excel',
    kind: 'excel',
    category: 'file',
    status: 'connected',
    health: 'healthy',
    cadence: 'manual',
    uri: 's3://shadow-intel/inbox/STR/*.xlsx',
    connectedAt: hoursAgo(720),
    lastSyncAt: hoursAgo(48),
    rowsIngested: 14_482,
    entitiesProduced: 4_482,
    edgesProduced: 14_111,
    owner: 'AML · STR',
    description: 'Suspicious Transaction Report worksheets · multi-sheet, normalized',
    errorCount: 0,
    credentialRef: 'iam:role/str-reader',
  },
];

/** Schema mappings — three real-shaped examples + the rest auto-suggested. */
export const INITIAL_MAPPINGS: Record<string, SchemaMapping> = {
  src_kyc_pg: {
    sourceId: 'src_kyc_pg',
    validatedAt: hoursAgo(96),
    entityRules: [
      { sourceField: 'customer_id', sampleValue: 'CUST-0xA124', targetEntity: 'person', confidence: 0.98, autoSuggested: true, validated: true },
      { sourceField: 'legal_name', sampleValue: 'A. Voss', targetEntity: 'person', confidence: 0.94, autoSuggested: true, validated: true },
      { sourceField: 'corp_legal_name', sampleValue: 'Obsidian Holdings BVI', targetEntity: 'shell_company', confidence: 0.88, autoSuggested: true, validated: true },
      { sourceField: 'registered_address', sampleValue: '17 Demetriou, Nicosia', targetEntity: 'address', confidence: 0.96, autoSuggested: true, validated: true },
      { sourceField: 'document_id', sampleValue: 'PASS-AT-08412', targetEntity: 'document', confidence: 0.84, autoSuggested: true, validated: true },
      { sourceField: 'device_fingerprint', sampleValue: 'fp_d4a1...', targetEntity: 'device', confidence: 0.92, autoSuggested: true, validated: true },
    ],
    edgeRules: [
      { fromField: 'customer_id', toField: 'corp_legal_name', edgeKind: 'controls', confidence: 0.86, autoSuggested: true },
      { fromField: 'customer_id', toField: 'registered_address', edgeKind: 'shares_address', confidence: 0.78, autoSuggested: true },
      { fromField: 'customer_id', toField: 'device_fingerprint', edgeKind: 'shares_device', confidence: 0.91, autoSuggested: true },
    ],
  },
  src_payments_kafka: {
    sourceId: 'src_payments_kafka',
    validatedAt: hoursAgo(240),
    entityRules: [
      { sourceField: 'txn_id', sampleValue: 'TXN-9f1a...', targetEntity: 'transaction', confidence: 0.99, autoSuggested: true, validated: true },
      { sourceField: 'src_account', sampleValue: 'EU-3320', targetEntity: 'account', confidence: 0.96, autoSuggested: true, validated: true },
      { sourceField: 'dst_account', sampleValue: 'ZR-4781', targetEntity: 'account', confidence: 0.96, autoSuggested: true, validated: true },
      { sourceField: 'merchant_id', sampleValue: 'MRCH-1188', targetEntity: 'company', confidence: 0.82, autoSuggested: true, validated: true },
    ],
    edgeRules: [
      { fromField: 'src_account', toField: 'dst_account', edgeKind: 'transfers', confidence: 0.97, autoSuggested: true },
      { fromField: 'src_account', toField: 'txn_id', edgeKind: 'transfers', confidence: 0.99, autoSuggested: true },
    ],
  },
  src_chain_eth: {
    sourceId: 'src_chain_eth',
    validatedAt: hoursAgo(72),
    entityRules: [
      { sourceField: 'from_address', sampleValue: '0xA9..b2', targetEntity: 'wallet', confidence: 0.99, autoSuggested: true, validated: true },
      { sourceField: 'to_address', sampleValue: '0xC1..7e', targetEntity: 'wallet', confidence: 0.99, autoSuggested: true, validated: true },
      { sourceField: 'tx_hash', sampleValue: '0x83a2...', targetEntity: 'transaction', confidence: 0.99, autoSuggested: true, validated: true },
      { sourceField: 'contract_address', sampleValue: '0x52..a0', targetEntity: 'company', confidence: 0.74, autoSuggested: true, validated: false },
    ],
    edgeRules: [
      { fromField: 'from_address', toField: 'to_address', edgeKind: 'transfers', confidence: 0.98, autoSuggested: true },
    ],
  },
  // For src_graphql_addr — auto-suggested but NOT validated, demonstrating an "awaiting analyst review" state
  src_graphql_addr: {
    sourceId: 'src_graphql_addr',
    entityRules: [
      { sourceField: 'address_id', sampleValue: 'ADDR-EU-001', targetEntity: 'address', confidence: 0.94, autoSuggested: true, validated: false },
      { sourceField: 'street_line', sampleValue: '2 Aulestrasse', targetEntity: 'address', confidence: 0.88, autoSuggested: true, validated: false },
      { sourceField: 'occupant_id', sampleValue: 'OCC-08812', targetEntity: 'person', confidence: 0.62, autoSuggested: true, validated: false },
      { sourceField: 'registered_entity', sampleValue: 'Helix Trust GP', targetEntity: 'shell_company', confidence: 0.74, autoSuggested: true, validated: false },
    ],
    edgeRules: [
      { fromField: 'occupant_id', toField: 'address_id', edgeKind: 'shares_address', confidence: 0.72, autoSuggested: true },
    ],
  },
};

/** Ingestion run history — last 24h across active sources */
export const INITIAL_RUNS: IngestionRun[] = [
  {
    id: 'run_pay_001',
    sourceId: 'src_payments_kafka',
    startedAt: minutesAgo(0),
    status: 'running',
    rowsRead: 18_402,
    entitiesAdded: 408,
    edgesAdded: 911,
    ringsDiscovered: 0,
    hiddenLinksFound: 2,
    errors: 0,
    log: [
      'consumer attached · partition 0 · offset 482_881_402',
      'extracting transactions · batch 1/8',
      'entity dedupe · 102 candidates · 4 new',
      'edge propagation · 311 wires',
    ],
  },
  {
    id: 'run_kyc_002',
    sourceId: 'src_kyc_pg',
    startedAt: minutesAgo(4),
    finishedAt: minutesAgo(3),
    status: 'success',
    rowsRead: 41_022,
    entitiesAdded: 88,
    edgesAdded: 412,
    ringsDiscovered: 0,
    hiddenLinksFound: 1,
    errors: 0,
    log: [
      'connected · pgbouncer pool 12/64',
      'incremental cursor · updated_at > 2024-06-21T11:48:02Z',
      'mapping applied · 6 entity rules · 3 edge rules',
      'graph sync · ✓',
    ],
  },
  {
    id: 'run_wires_003',
    sourceId: 'src_wires_snow',
    startedAt: minutesAgo(38),
    finishedAt: minutesAgo(35),
    status: 'success',
    rowsRead: 11_204,
    entitiesAdded: 24,
    edgesAdded: 188,
    ringsDiscovered: 1,
    hiddenLinksFound: 0,
    errors: 0,
    log: [
      'snowflake warehouse · FRAUD_WH (MEDIUM) · resumed',
      'query · 11,204 rows in 12.4s',
      'ring detector flagged Obsidian → Helix → Kappa → Orchid',
      'graph sync · ✓',
    ],
  },
  {
    id: 'run_csv_004',
    sourceId: 'src_card_csv',
    startedAt: hoursAgo(11),
    finishedAt: hoursAgo(11),
    status: 'partial',
    rowsRead: 482_011,
    entitiesAdded: 18_402,
    edgesAdded: 41_402,
    ringsDiscovered: 0,
    hiddenLinksFound: 4,
    errors: 14,
    log: [
      's3://shadow-intel/inbox/card-declines/2024-06-20.csv',
      'parse · 482,011 / 482,025 rows · 14 rejected (malformed dates)',
      'mapping applied · 7 entity rules',
      'partial · graph sync ✓',
    ],
  },
  {
    id: 'run_webhook_005',
    sourceId: 'src_webhook_signals',
    startedAt: hoursAgo(2),
    finishedAt: hoursAgo(2),
    status: 'failed',
    rowsRead: 0,
    entitiesAdded: 0,
    edgesAdded: 0,
    ringsDiscovered: 0,
    hiddenLinksFound: 0,
    errors: 41,
    log: [
      'POST /in/risk-signals → 401 Unauthorized',
      'auth · bearer token rejected · check vault:vendor-risk-2024',
      'retry · exhausted (3/3)',
      'paged on-call: alert sent',
    ],
  },
];

export { now };
